
services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:21.0.1
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    command: start-dev
#    ports:
#      - "8080:8080"
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
    depends_on:
      - keycloak
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
      - keycloak

#  postgres:
#    image: postgres:latest
#    container_name: pg-skillhub
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5433:5432"
#    networks:
#      - skillhub-net

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "5050:80"
#    networks:
#      - skillhub-net

networks:
  skillhub-net:
    driver: bridge
